### ISSUE TITLE
Strange error when trying to run rofi-copyq on PopOS 20.10

### ISSUE THREAD

**Issue by ghost** [cjbassi/rofi-copyq#4]
Traceback (most recent call last):
  File "/home/dappercore/.local/bin/rofi-copyq", line 25, in <module>
    json_arr = json.loads(p.stdout)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I just cloned the pip installed, logged out and logged back in, tried running the command, and was greeted with that error.

**Comment by pirog-x** [comment]
I have the same problem
